spring:
  application:
    name: viro-provider-ai

  jackson:
    #  格式化返回时间 yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


server:
  servlet:
    context-path: "/viro/ai"
